env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: ['*.svelte']
    processor: svelte3/svelte3
plugins:
  - '@typescript-eslint'
  - 'svelte3'
rules: 
  semi: 
    - error
    - never
settings:
  svelte3/typescript: true
