b/asePath: /api
consumes:
- application/json
- text/vnd.yaml
- application/toml
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      name: token
security:
  - cookieAuth: []
definitions:
  ProjectInput:
    type: object
    required:
      - title
      - short_name
    properties:
      title:
        type: string
        minLength: 1
        maxLength: 400
      short_name:
        type: string
        minLength: 1
        maxLength: 20
      description:
        type: string
        minLength: 1
        maxLength: 8000
  TranslationInput:
    type: object
    required:
      - category_id
      - key
    properties:
      category_id:
        type: string
        minLength: 3
        maxLength: 100
      key:
        type: string
        pattern: ^[^\s]*$
        minLength: 1
        maxLength: 400
      context:
        type: string
        pattern: ^[^\s]*$
        minLength: 1
        maxLength: 400
      title:
        type: string
        minLength: 1
        maxLength: 400
      description:
        type: string
        minLength: 1
        maxLength: 8000
        
  LocaleInput:
    type: object
    required: 
      - iso639_1
      - iso639_2
      - iso639_3
      - ietf_tag
      - title
    properties:
      title:
        type: string
        minLength: 3
        maxLength: 300
      iso639_1:
        type: string
        minLength: 2
        maxLength: 2
      iso639_2:
        type: string
        minLength: 3
        maxLength: 3
      iso639_3:
        type: string
        minLength: 3
        maxLength: 3
      ietf_tag:
        type: string
        description: List of other Locales in preferred order for fallbacks
        minLength: 2
        maxLength: 12


  TranslationValueInput:
    properties:
      translation_id:
        maxLength: 100
        minLength: 1
        type: string
      locale_id:
        maxLength: 100
        minLength: 1
        type: string
      value:
        maxLength: 8000
        minLength: 0
        type: string
    type: object
    required:
      - translation_id
      - locale_id
      - value
  ReportMissingInput:
    type: object
    additionalProperties:
      type: string
  CategoryInput:
    properties:
      key:
        maxLength: 100
        minLength: 1
        pattern: ^[^\s]*$
        type: string
      project_id:
        maxLength: 100
        minLength: 1
        type: string
      title:
        maxLength: 400
        minLength: 3
        type: string
      description:
        maxLength: 8000
        minLength: 3
        type: string
    type: object
    required:
      - key
      - project_id
      - title
  LoginInput:
    properties:
      password:
        maxLength: 400
        minLength: 3
        type: string
      username:
        example: abc123
        maxLength: 100
        minLength: 3
        pattern: ^[^\s]*$
        type: string
    type: object
    required:
      - username
      - password
host: localhost
info:
  description: >
    Api fo Skiver-api.
    <a href="https://insomnia.rest/run/?label=&uri=" target="_blank"><img src="https://insomnia.rest/images/run.svg" alt="Run in Insomnia"></a>

    # About formatting

    This api produces output in json, yaml and toml. Every api-route takes parameters for controlling which content-type should be produced.

    In General, you can control this with these parameters:

      - `Accept`-header
      - Appending `.json`/`.yaml`/`.toml` to the path (not all routes supports this.)
      - `out_format`-query-parameter
      - `Content-Type`-header

  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  title: Skiver API.
  version: 0.0.1
paths:
  /api/missing/{locale}/{project}:
    post: 
    tags:
      - translation
    summary: Missing translations reported by users
    operationId: reportMissing
    parameters:
      - in: path
        name: project
        type: string
        required: true
        description: >
          The parameter can be any of the Project's ID or ShortName.
      - in: path
        name: locale
        type: string
        required: true
        description: >
          The parameter can be any of the Locale's ID, iso639_1, iso639_2, iso639_3, or ietf_tag.
      - in: body
        name: ReportMissingPayload
        schema:
          $ref: '#/definitions/ReportMissingInput'
  /api/export/:
    get:
      tags:
        - export
      summary: Returnes a snapshot of the set of translations.
      description: >
        For caching in browsers, proxy caching services etc. to work consistenly with parameters, the `?`-prefix for the query-parameters should be removed.
       
        Note that by default, output-maps are flattened when requesting only a single project/locale. Set the parameter `no_flatten` to override.

      operationId: getExport
      parameters:
        - in: query
          name: project
          required: false
          type: string
          description: >
            The parameter can be any of the Project's ID or ShortName.

            The short-alias for this parameter is: `p`
        - in: query
          name: format
          required: false
          type: string
          enum:
            - raw
            - i18n
          description: >
            Used to set the export-format.

            ### `i18n`

            The output is formatted to be i18n-compliant.
            
            ### `raw`

            The output is not converted, and all data is outputted.

            The short-alias for this parameter is: `f`
        - in: query
          name: no_flatten
          required: false
          type: boolean
          description: >
            Disables flattening of the outputet map
        - in: query
          name: locale_key
          type: string
          required: false
          description: >
            Used to set which key in output for the locale that should be used.
            
            The parameter can be any of the Locale's ID, iso639_1, iso639_2, iso639_3, or ietf_tag.

            The short-alias for this parameter is: `p`
        - in: query
          name: locale
          type: string
          required: false
          description: >
            The parameter can be any of the Locale's ID, iso639_1, iso639_2, iso639_3, or ietf_tag.

            By leaving out the parameters, all locales will be returned.
            
            The short-alias for this parameter is: `l`

            **Future: By setting `locale_id=auto`, the server will infer the locale from the browsers headers.**
            
      responses:
        "200":
          description: "key-value i18n-type response."
          schema:
            type: object
        "404":
          $ref: '#/responses/apiError'
        "500":
          $ref: '#/responses/apiError'

  /api/serverInfo/:
    get:
      summary: Information about the server
      operationId: getServerInfo
      responses:
        "200":
          $ref: '#/responses/serverInfo'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - server
  /api/project/:
    get:
      summary: List projects
      operationId: getProject
      responses:
        "200":
          $ref: '#/responses/ProjectsResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - project
    post:
      summary: Create a new project
      operationId: createProject
      responses:
        "200":
          $ref: '#/responses/ProjectResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - project
  /api/category/:
    get:
      summary: List categories
      operationId: getcategory
      responses:
        "200":
          $ref: '#/responses/CategoryResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - category
    post:
      summary: Create a new category
      operationId: createCategory
      responses:
        "200":
          $ref: '#/responses/CategoryResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - category
  /api/translation/:
    get:
      summary: List translations
      operationId: getTranslation
      responses:
        "200":
          $ref: '#/responses/TranslationsResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - translation
    post:
      summary: Create a new translation
      operationId: createTranslation
      responses:
        "200":
          $ref: '#/responses/TranslationResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - translation
  /api/translation-value/:
    get:
      summary: List translation-values
      operationId: getTranslationValue
      responses:
        "200":
          $ref: '#/responses/TranslationValuesResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - translationValue
    post:
      summary: Create a new translation-value for a locale
      operationId: createTranslationValue
      responses:
        "200":
          $ref: '#/responses/TranslationValueResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - translationValue
  /api/login/:
    get:
      summary: Get login-information
      description: "Returns information about the logged in user"
      operationId: getLogin
      responses:
        "200":
          $ref: '#/responses/loginResponse'
        "403":
          $ref: '#/responses/apiError'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - auth
    post:
      security: []
      summary: Login
      description: Login to aquire a token, set in a cookie
      operationId: login
      parameters:
      - in: body
        required: true
        name: LoginInput
        schema:
          $ref: '#/definitions/LoginInput'
      responses:
        "200":
          $ref: '#/responses/loginResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - auth
  /api/locale/:
    post:
      summary: Create a locale
      operationId: listLocale
      parameters:
      - in: body
        required: true
        name: LocaleInput
        schema:
          $ref: '#/definitions/LocaleInput'
      responses:
        "200":
          $ref: '#/responses/localeResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - locale
    get:
      summary: List locales
      operationId: getLocale
      responses:
        "200":
          $ref: '#/responses/LocalesResponse'
        "500":
          $ref: '#/responses/apiError'
      tags:
      - locale
produces:
- application/json
- text/vnd.yaml
- application/toml
responses:
  apiError:
    description: "Consistant error-codes"
    schema:
      $ref: '#/definitions/ApiError'
  loginResponse:
    description: >
      On successful authentication, the token is set in a cookie named 'token'.

      For subsequent requests, you need to include the token.
      Browsers typically do this automatically (CORS).

      The token is by default valid for one hour.
    headers:
      Set-Cookie:
        type: string
        schema:
          type: string
          example: token=b6f7502c-2d39-4ddb-9890-84cb10d9bd13; Max-Age=3600; HttpOnly
    schema:
      $ref: '#/definitions/LoginResponse'
      type: object
  LocalesResponse:
    description: ""
    schema:
      items:
        $ref: '#/definitions/Locale'
      type: array
  ProjectResponse:
    description: ""
    schema:
      $ref: '#/definitions/Project'
      type: object
  ProjectsResponse:
    description: ""
    schema:
      items:
        $ref: '#/definitions/Project'
      type: array
  CategoryResponse:
    description: ""
    schema:
      $ref: '#/definitions/Category'
      type: object
  CategoriesResponse:
    description: ""
    schema:
      items:
        $ref: '#/definitions/Category'
      type: array
  TranslationResponse:
    description: ""
    schema:
      $ref: '#/definitions/Translation'
      type: object
  TranslationsResponse:
    description: ""
    schema:
      items:
        $ref: '#/definitions/Translation'
      type: array
  TranslationValueResponse:
    description: ""
    schema:
      $ref: '#/definitions/TranslationValue'
      type: object
  TranslationValuesResponse:
    description: ""
    schema:
      items:
        $ref: '#/definitions/TranslationValue'
      type: array
schemes:
- http
swagger: "2.0"
tags: 
  - name: project
    description: More or less like a folder
  - name: locale
    description: Language-like
  - name: translation
    description: The specific translation of some key
  - name: auth
    description: Authentication and Authorization
