# https://fly.io/docs/reference/configuration/

app = "skiver"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[build]
  image = "runardocker/skiver-api:latest"

[deploy]
  strategy = "rolling"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
port = 9091 # default for most prometheus clients
path = "/metrics" # default for most prometheus clients
[[mounts]]
source="skiver_data"
destination="/storage"
[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    # Until postgres is available, we don't really support concurrency
    hard_limit = 999999
    soft_limit = 999999
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
