export const iconMap = {
  add: 'fa-plus',
  edit: 'fa-edit',
  code: 'fa-code',
  create: 'fa-plus',
  cancel: 'fa-ban',
  submit: 'fa-paper-plane',
  collapseUp: 'fa-angle-up',
  collapseDown: 'fa-angle-down',
  closeCross: 'fa-times',
  gEndpoint: 'fa-ethernet',
  gRequest: 'fa-network-wired',
  gStat: 'fa-chart-bar',
  gSchedule: 'fa-calendar',
  error: 'fa-exclamation-circle',
  warning: 'fa-exclamation-triangle',
  info: 'fa-info',
  success: 'fa-check',
  delete: 'fa-trash',
  copy: 'fa-copy',
  clock: 'fa-clock',
  refresh: 'fa-sync',
  play: 'fa-play',
  toggleOn: 'fa-toggle-on',
  toggleOff: 'fa-toggle-off',
  signIn: 'fa-sign-in-alt',
  menu: 'fas fa-hamburger',
  settings: 'fas fa-sliders-h',
  loading: 'fad fa-spinner fa-spin',
  arrowDown: 'fas fa-arrow-down',
  openModal: 'fas fa-arrow-circle-up',
  longArrowRight: 'fas fa-long-arrow-alt-right'
} as const

export type Icon = keyof typeof iconMap
