// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CategoryInput category input
//
// swagger:model CategoryInput
type CategoryInput struct {

	// description
	// Max Length: 8000
	// Min Length: 3
	Description string `json:"description,omitempty"`

	// key
	// Required: true
	// Max Length: 100
	// Min Length: 1
	// Pattern: ^[^\s]*$
	Key *string `json:"key"`

	// project id
	// Required: true
	// Max Length: 100
	// Min Length: 1
	ProjectID *string `json:"project_id"`

	// title
	// Required: true
	// Max Length: 400
	// Min Length: 3
	Title *string `json:"title"`
}

// Validate validates this category input
func (m *CategoryInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CategoryInput) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MinLength("description", "body", m.Description, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("description", "body", m.Description, 8000); err != nil {
		return err
	}

	return nil
}

func (m *CategoryInput) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	if err := validate.MinLength("key", "body", *m.Key, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("key", "body", *m.Key, 100); err != nil {
		return err
	}

	if err := validate.Pattern("key", "body", *m.Key, `^[^\s]*$`); err != nil {
		return err
	}

	return nil
}

func (m *CategoryInput) validateProjectID(formats strfmt.Registry) error {

	if err := validate.Required("project_id", "body", m.ProjectID); err != nil {
		return err
	}

	if err := validate.MinLength("project_id", "body", *m.ProjectID, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("project_id", "body", *m.ProjectID, 100); err != nil {
		return err
	}

	return nil
}

func (m *CategoryInput) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	if err := validate.MinLength("title", "body", *m.Title, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("title", "body", *m.Title, 400); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this category input based on context it is used
func (m *CategoryInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CategoryInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategoryInput) UnmarshalBinary(b []byte) error {
	var res CategoryInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
