// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CategoryTreeNode category tree node
//
// swagger:model CategoryTreeNode
type CategoryTreeNode struct {

	// categories
	Categories map[string]CategoryTreeNode `json:"categories,omitempty"`

	// Time of which the entity was created in the database
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"created_at"`

	// User id refering to the user who created the item
	CreatedBy string `json:"created_by,omitempty"`

	// If set, the item is considered deleted. The item will normally not get deleted from the database,
	// but it may if cleanup is required.
	// Format: date-time
	Deleted strfmt.DateTime `json:"deleted,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// TODO: change to map
	Exists bool `json:"exists,omitempty"`

	// Unique identifier of the entity
	// Required: true
	ID *string `json:"id"`

	// key
	Key string `json:"key,omitempty"`

	// project ID
	ProjectID string `json:"project_id,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// translation i ds
	TranslationIDs []string `json:"translation_ids"`

	// translations
	Translations map[string]ExtendedTranslation `json:"translations,omitempty"`

	// Time of which the entity was updated, if any
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`

	// User id refering to who created the item
	UpdatedBy string `json:"updated_by,omitempty"`
}

// Validate validates this category tree node
func (m *CategoryTreeNode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategories(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeleted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTranslations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CategoryTreeNode) validateCategories(formats strfmt.Registry) error {
	if swag.IsZero(m.Categories) { // not required
		return nil
	}

	for k := range m.Categories {

		if err := validate.Required("categories"+"."+k, "body", m.Categories[k]); err != nil {
			return err
		}
		if val, ok := m.Categories[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *CategoryTreeNode) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CategoryTreeNode) validateDeleted(formats strfmt.Registry) error {
	if swag.IsZero(m.Deleted) { // not required
		return nil
	}

	if err := validate.FormatOf("deleted", "body", "date-time", m.Deleted.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CategoryTreeNode) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *CategoryTreeNode) validateTranslations(formats strfmt.Registry) error {
	if swag.IsZero(m.Translations) { // not required
		return nil
	}

	for k := range m.Translations {

		if err := validate.Required("translations"+"."+k, "body", m.Translations[k]); err != nil {
			return err
		}
		if val, ok := m.Translations[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *CategoryTreeNode) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this category tree node based on the context it is used
func (m *CategoryTreeNode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCategories(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTranslations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CategoryTreeNode) contextValidateCategories(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Categories {

		if val, ok := m.Categories[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *CategoryTreeNode) contextValidateTranslations(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Translations {

		if val, ok := m.Translations[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CategoryTreeNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategoryTreeNode) UnmarshalBinary(b []byte) error {
	var res CategoryTreeNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
