// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Change Change stores information about a changed item
//
// swagger:model Change
type Change struct {

	// from
	From interface{} `json:"from,omitempty"`

	// path
	Path []string `json:"path"`

	// to
	To interface{} `json:"to,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this change
func (m *Change) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this change based on context it is used
func (m *Change) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Change) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Change) UnmarshalBinary(b []byte) error {
	var res Change
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
