// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChangePasswordInput change password input
//
// swagger:model ChangePasswordInput
type ChangePasswordInput struct {

	// password
	// Required: true
	// Max Length: 2000
	// Min Length: 3
	Password *string `json:"password"`
}

// Validate validates this change password input
func (m *ChangePasswordInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChangePasswordInput) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", *m.Password, 2000); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this change password input based on context it is used
func (m *ChangePasswordInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangePasswordInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangePasswordInput) UnmarshalBinary(b []byte) error {
	var res ChangePasswordInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
