// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateTokenInput create token input
//
// swagger:model CreateTokenInput
type CreateTokenInput struct {

	// description
	// Required: true
	// Max Length: 200
	// Min Length: 3
	Description *string `json:"description"`

	// Duration in hours of which the token should be valid
	// Required: true
	TTLHours *int64 `json:"ttl_hours"`
}

// Validate validates this create token input
func (m *CreateTokenInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTTLHours(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateTokenInput) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	if err := validate.MinLength("description", "body", *m.Description, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("description", "body", *m.Description, 200); err != nil {
		return err
	}

	return nil
}

func (m *CreateTokenInput) validateTTLHours(formats strfmt.Registry) error {

	if err := validate.Required("ttl_hours", "body", m.TTLHours); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create token input based on context it is used
func (m *CreateTokenInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTokenInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTokenInput) UnmarshalBinary(b []byte) error {
	var res CreateTokenInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
