// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CreatorSource creator source
//
// swagger:model CreatorSource
type CreatorSource string

// Validate validates this creator source
func (m CreatorSource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this creator source based on context it is used
func (m CreatorSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
