// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LoginInput login input
//
// swagger:model LoginInput
type LoginInput struct {

	// password
	// Required: true
	// Max Length: 400
	// Min Length: 3
	Password *string `json:"password"`

	// username
	// Example: abc123
	// Required: true
	// Max Length: 100
	// Min Length: 3
	// Pattern: ^[^\s]*$
	Username *string `json:"username"`
}

// Validate validates this login input
func (m *LoginInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LoginInput) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", *m.Password, 400); err != nil {
		return err
	}

	return nil
}

func (m *LoginInput) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	if err := validate.MinLength("username", "body", *m.Username, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("username", "body", *m.Username, 100); err != nil {
		return err
	}

	if err := validate.Pattern("username", "body", *m.Username, `^[^\s]*$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this login input based on context it is used
func (m *LoginInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginInput) UnmarshalBinary(b []byte) error {
	var res LoginInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
