// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectSnapshotMeta project snapshot meta
//
// swagger:model ProjectSnapshotMeta
type ProjectSnapshotMeta struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// created by
	CreatedBy string `json:"created_by,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// hash
	Hash uint64 `json:"hash,omitempty"`

	// snapshot ID
	SnapshotID string `json:"id,omitempty"`

	// upload meta
	UploadMeta []*UploadMeta `json:"uploadMeta"`
}

// Validate validates this project snapshot meta
func (m *ProjectSnapshotMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUploadMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectSnapshotMeta) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ProjectSnapshotMeta) validateUploadMeta(formats strfmt.Registry) error {
	if swag.IsZero(m.UploadMeta) { // not required
		return nil
	}

	for i := 0; i < len(m.UploadMeta); i++ {
		if swag.IsZero(m.UploadMeta[i]) { // not required
			continue
		}

		if m.UploadMeta[i] != nil {
			if err := m.UploadMeta[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("uploadMeta" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("uploadMeta" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this project snapshot meta based on the context it is used
func (m *ProjectSnapshotMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUploadMeta(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectSnapshotMeta) contextValidateUploadMeta(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.UploadMeta); i++ {

		if m.UploadMeta[i] != nil {
			if err := m.UploadMeta[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("uploadMeta" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("uploadMeta" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProjectSnapshotMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectSnapshotMeta) UnmarshalBinary(b []byte) error {
	var res ProjectSnapshotMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
