// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ReportMissingInput report missing input
//
// swagger:model ReportMissingInput
type ReportMissingInput map[string]string

// Validate validates this report missing input
func (m ReportMissingInput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this report missing input based on context it is used
func (m ReportMissingInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
