// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SimpleUser simple user
//
// swagger:model SimpleUser
type SimpleUser string

// Validate validates this simple user
func (m SimpleUser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this simple user based on context it is used
func (m SimpleUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
