// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TranslationValueInput translation value input
//
// swagger:model TranslationValueInput
type TranslationValueInput struct {

	// If set, it will add/update the context for that key instead of the original value
	// Max Length: 100
	// Min Length: 1
	// Pattern: ^[^\s]*$
	ContextKey string `json:"context_key,omitempty"`

	// locale id
	// Required: true
	// Max Length: 100
	// Min Length: 1
	LocaleID *string `json:"locale_id"`

	// translation id
	// Required: true
	// Max Length: 100
	// Min Length: 1
	TranslationID *string `json:"translation_id"`

	// value
	// Max Length: 8000
	// Min Length: 0
	Value *string `json:"value,omitempty"`
}

// Validate validates this translation value input
func (m *TranslationValueInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContextKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocaleID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTranslationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TranslationValueInput) validateContextKey(formats strfmt.Registry) error {
	if swag.IsZero(m.ContextKey) { // not required
		return nil
	}

	if err := validate.MinLength("context_key", "body", m.ContextKey, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("context_key", "body", m.ContextKey, 100); err != nil {
		return err
	}

	if err := validate.Pattern("context_key", "body", m.ContextKey, `^[^\s]*$`); err != nil {
		return err
	}

	return nil
}

func (m *TranslationValueInput) validateLocaleID(formats strfmt.Registry) error {

	if err := validate.Required("locale_id", "body", m.LocaleID); err != nil {
		return err
	}

	if err := validate.MinLength("locale_id", "body", *m.LocaleID, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("locale_id", "body", *m.LocaleID, 100); err != nil {
		return err
	}

	return nil
}

func (m *TranslationValueInput) validateTranslationID(formats strfmt.Registry) error {

	if err := validate.Required("translation_id", "body", m.TranslationID); err != nil {
		return err
	}

	if err := validate.MinLength("translation_id", "body", *m.TranslationID, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("translation_id", "body", *m.TranslationID, 100); err != nil {
		return err
	}

	return nil
}

func (m *TranslationValueInput) validateValue(formats strfmt.Registry) error {
	if swag.IsZero(m.Value) { // not required
		return nil
	}

	if err := validate.MinLength("value", "body", *m.Value, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("value", "body", *m.Value, 8000); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this translation value input based on context it is used
func (m *TranslationValueInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TranslationValueInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TranslationValueInput) UnmarshalBinary(b []byte) error {
	var res TranslationValueInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
