// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TranslationInput translation input
//
// swagger:model TranslationInput
type TranslationInput struct {

	// category id
	// Required: true
	// Max Length: 100
	// Min Length: 3
	CategoryID *string `json:"category_id"`

	// description
	// Max Length: 8000
	// Min Length: 1
	Description string `json:"description,omitempty"`

	// key
	// Required: true
	// Max Length: 400
	// Min Length: 1
	// Pattern: ^[^\s]*$
	Key *string `json:"key"`

	// title
	// Max Length: 400
	// Min Length: 1
	Title string `json:"title,omitempty"`
}

// Validate validates this translation input
func (m *TranslationInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCategoryID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TranslationInput) validateCategoryID(formats strfmt.Registry) error {

	if err := validate.Required("category_id", "body", m.CategoryID); err != nil {
		return err
	}

	if err := validate.MinLength("category_id", "body", *m.CategoryID, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("category_id", "body", *m.CategoryID, 100); err != nil {
		return err
	}

	return nil
}

func (m *TranslationInput) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MinLength("description", "body", m.Description, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("description", "body", m.Description, 8000); err != nil {
		return err
	}

	return nil
}

func (m *TranslationInput) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	if err := validate.MinLength("key", "body", *m.Key, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("key", "body", *m.Key, 400); err != nil {
		return err
	}

	if err := validate.Pattern("key", "body", *m.Key, `^[^\s]*$`); err != nil {
		return err
	}

	return nil
}

func (m *TranslationInput) validateTitle(formats strfmt.Registry) error {
	if swag.IsZero(m.Title) { // not required
		return nil
	}

	if err := validate.MinLength("title", "body", m.Title, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("title", "body", m.Title, 400); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this translation input based on context it is used
func (m *TranslationInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TranslationInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TranslationInput) UnmarshalBinary(b []byte) error {
	var res TranslationInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
