// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateProjectInput update project input
//
// swagger:model UpdateProjectInput
type UpdateProjectInput struct {

	// description
	// Max Length: 8000
	// Min Length: 1
	Description string `json:"description,omitempty"`

	// id
	// Required: true
	// Max Length: 36
	// Min Length: 3
	ID *string `json:"id"`

	// locales
	Locales map[string]LocaleSettingInput `json:"locales,omitempty"`

	// short name
	// Max Length: 20
	// Min Length: 1
	// Pattern: ^[a-z1-9]*$
	ShortName string `json:"short_name,omitempty"`

	// title
	// Max Length: 400
	// Min Length: 1
	Title string `json:"title,omitempty"`
}

// Validate validates this update project input
func (m *UpdateProjectInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocales(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateShortName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateProjectInput) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MinLength("description", "body", m.Description, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("description", "body", m.Description, 8000); err != nil {
		return err
	}

	return nil
}

func (m *UpdateProjectInput) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.MinLength("id", "body", *m.ID, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", *m.ID, 36); err != nil {
		return err
	}

	return nil
}

func (m *UpdateProjectInput) validateLocales(formats strfmt.Registry) error {
	if swag.IsZero(m.Locales) { // not required
		return nil
	}

	for k := range m.Locales {

		if err := validate.Required("locales"+"."+k, "body", m.Locales[k]); err != nil {
			return err
		}
		if val, ok := m.Locales[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *UpdateProjectInput) validateShortName(formats strfmt.Registry) error {
	if swag.IsZero(m.ShortName) { // not required
		return nil
	}

	if err := validate.MinLength("short_name", "body", m.ShortName, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("short_name", "body", m.ShortName, 20); err != nil {
		return err
	}

	if err := validate.Pattern("short_name", "body", m.ShortName, `^[a-z1-9]*$`); err != nil {
		return err
	}

	return nil
}

func (m *UpdateProjectInput) validateTitle(formats strfmt.Registry) error {
	if swag.IsZero(m.Title) { // not required
		return nil
	}

	if err := validate.MinLength("title", "body", m.Title, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("title", "body", m.Title, 400); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this update project input based on the context it is used
func (m *UpdateProjectInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLocales(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateProjectInput) contextValidateLocales(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Locales {

		if val, ok := m.Locales[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateProjectInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateProjectInput) UnmarshalBinary(b []byte) error {
	var res UpdateProjectInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
