// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// User user
//
// swagger:model User
type User struct {

	// If not active, the account cannot be used until any issues are resolved.
	Active bool `json:"active,omitempty"`

	// can create locales
	CanCreateLocales bool `json:"can_create_locales,omitempty"`

	// can create organization
	CanCreateOrganization bool `json:"can_create_organization,omitempty"`

	// can create projects
	CanCreateProjects bool `json:"can_create_projects,omitempty"`

	// can create translations
	CanCreateTranslations bool `json:"can_create_translations,omitempty"`

	// can create users
	CanCreateUsers bool `json:"can_create_users,omitempty"`

	// can manage snapshots
	CanManageSnapshots bool `json:"can_manage_snapshots,omitempty"`

	// can update locales
	CanUpdateLocales bool `json:"can_update_locales,omitempty"`

	// can update organization
	CanUpdateOrganization bool `json:"can_update_organization,omitempty"`

	// can update projects
	CanUpdateProjects bool `json:"can_update_projects,omitempty"`

	// can update translations
	CanUpdateTranslations bool `json:"can_update_translations,omitempty"`

	// can update users
	CanUpdateUsers bool `json:"can_update_users,omitempty"`

	// Time of which the entity was created in the database
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"created_at"`

	// User id refering to the user who created the item
	CreatedBy string `json:"created_by,omitempty"`

	// If set, the item is considered deleted. The item will normally not get deleted from the database,
	// but it may if cleanup is required.
	// Format: date-time
	Deleted strfmt.DateTime `json:"deleted,omitempty"`

	// Unique identifier of the entity
	// Required: true
	ID *string `json:"id"`

	// If set, the user must change the password before the account can be used
	TemporaryPassword bool `json:"temporary_password,omitempty"`

	// Time of which the entity was updated, if any
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`

	// User id refering to who created the item
	UpdatedBy string `json:"updated_by,omitempty"`

	// user name
	UserName string `json:"username,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeleted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *User) validateDeleted(formats strfmt.Registry) error {
	if swag.IsZero(m.Deleted) { // not required
		return nil
	}

	if err := validate.FormatOf("deleted", "body", "date-time", m.Deleted.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *User) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *User) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user based on context it is used
func (m *User) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
